// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Citi
    {
        public Citi()
        {
            Stock = new HashSet<Stock>();
            Supplier = new HashSet<Supplier>();
        }

        public int Id_cities { get; set; }
        public string name { get; set; }

        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}