// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Discount
    {
        public Discount()
        {
            Order = new HashSet<Order>();
        }

        public int Id_discounts { get; set; }
        public int percent { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}