// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Good
    {
        public Good()
        {
            Goods_in_stocks = new HashSet<Goods_in_stocks>();
            Order = new HashSet<Order>();
            Supply = new HashSet<Supply>();
        }

        public int Id_goods { get; set; }
        public int Id_category { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public decimal Price_per_centner { get; set; }
        public byte[] picture { get; set; }

        public virtual Сategory Id_categoryNavigation { get; set; }
        public virtual ICollection<Goods_in_stocks> Goods_in_stocks { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Supply> Supply { get; set; }
    }
}