// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Goods_in_stocks
    {
        public int Id_stocks { get; set; }
        public int Id_goods { get; set; }
        public int Numbet_of_cetners { get; set; }

        public virtual Good Id_goodsNavigation { get; set; }
        public virtual Stock Id_stocksNavigation { get; set; }
    }
}