// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Stock
    {
        public Stock()
        {
            Goods_in_stocks = new HashSet<Goods_in_stocks>();
            Order = new HashSet<Order>();
            Supply = new HashSet<Supply>();
        }

        public int Id_stocks { get; set; }
        public int Id_cities { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string building { get; set; }

        public virtual Citi Id_citiesNavigation { get; set; }
        public virtual ICollection<Goods_in_stocks> Goods_in_stocks { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Supply> Supply { get; set; }
    }
}