// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class User
    {
        public User()
        {
            Order = new HashSet<Order>();
        }

        public int Id_users { get; set; }
        public int? Id_roles { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string phone_namber { get; set; }
        public string login { get; set; }
        public string password { get; set; }

        public virtual Role Id_rolesNavigation { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}