// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Desctop.Models
{
    public partial class Сategory
    {
        public Сategory()
        {
            Good = new HashSet<Good>();
        }

        public int Id_category { get; set; }
        public string title { get; set; }

        public virtual ICollection<Good> Good { get; set; }
    }
}